DROP TABLE IF EXISTS PRICES;

CREATE TABLE PRICES (
    UUID        UUID           NOT NULL PRIMARY KEY,
    BRAND_ID    BIGINT         NOT NULL,
    START_DATE  TIMESTAMP      NOT NULL,
    END_DATE    TIMESTAMP      NOT NULL,
    PRICE_LIST  BIGINT         NOT NULL,
    PRODUCT_ID  BIGINT         NOT NULL,
    PRIORITY    INT            NOT NULL,
    PRICE       DECIMAL(10, 2) NOT NULL,
    CURR        VARCHAR(3)     NOT NULL
);

CREATE INDEX IDX_PRICES_LOOKUP ON PRICES (BRAND_ID, PRODUCT_ID, START_DATE, END_DATE);
